import { TestQuestion } from '../types';

export const SST_TEST_QUESTIONS: TestQuestion[] = [
  { id: 'sst-1', question: 'Who was the first Prime Minister of India?', options: ['Jawaharlal Nehru', 'Mahatma Gandhi', 'Sardar Patel', 'B.R. Ambedkar'], correctAnswer: 0 },
  { id: 'sst-2', question: 'Which is the largest continent?', options: ['Africa', 'Asia', 'Europe', 'North America'], correctAnswer: 1 },
  { id: 'sst-3', question: 'When did India get independence?', options: ['1945', '1946', '1947', '1948'], correctAnswer: 2 },
  { id: 'sst-4', question: 'What is the capital of France?', options: ['Berlin', 'Madrid', 'Paris', 'Rome'], correctAnswer: 2 },
  { id: 'sst-5', question: 'Which river is the longest in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correctAnswer: 1 },
  { id: 'sst-6', question: 'Who wrote the Indian Constitution?', options: ['Mahatma Gandhi', 'Jawaharlal Nehru', 'B.R. Ambedkar', 'Subhash Chandra Bose'], correctAnswer: 2 },
  { id: 'sst-7', question: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], correctAnswer: 1 },
  { id: 'sst-8', question: 'What is the currency of Japan?', options: ['Yuan', 'Won', 'Yen', 'Ringgit'], correctAnswer: 2 },
  { id: 'sst-9', question: 'Which is the smallest country in the world?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], correctAnswer: 1 },
  { id: 'sst-10', question: 'Who discovered America?', options: ['Vasco da Gama', 'Christopher Columbus', 'James Cook', 'Marco Polo'], correctAnswer: 1 },
  { id: 'sst-11', question: 'Which is the highest mountain peak in the world?', options: ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'], correctAnswer: 2 },
  { id: 'sst-12', question: 'What is the capital of Italy?', options: ['Venice', 'Florence', 'Naples', 'Rome'], correctAnswer: 3 },
  { id: 'sst-13', question: 'Which ocean is the largest?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correctAnswer: 3 },
  { id: 'sst-14', question: 'Who was the first woman Prime Minister of India?', options: ['Pratibha Patil', 'Indira Gandhi', 'Sonia Gandhi', 'Sarojini Naidu'], correctAnswer: 1 },
  { id: 'sst-15', question: 'When was the United Nations founded?', options: ['1944', '1945', '1946', '1947'], correctAnswer: 1 },
  { id: 'sst-16', question: 'Which is the largest desert in the world?', options: ['Gobi', 'Sahara', 'Arabian', 'Kalahari'], correctAnswer: 1 },
  { id: 'sst-17', question: 'Who is known as the Iron Man of India?', options: ['Bhagat Singh', 'Sardar Patel', 'Lala Lajpat Rai', 'Bal Gangadhar Tilak'], correctAnswer: 1 },
  { id: 'sst-18', question: 'What is the capital of Russia?', options: ['Saint Petersburg', 'Moscow', 'Kazan', 'Novosibirsk'], correctAnswer: 1 },
  { id: 'sst-19', question: 'Which country is known as the Land of the Rising Sun?', options: ['China', 'Japan', 'South Korea', 'Thailand'], correctAnswer: 1 },
  { id: 'sst-20', question: 'Who was the first President of the USA?', options: ['Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'], correctAnswer: 2 },
];

export const SCIENCE_TEST_QUESTIONS: TestQuestion[] = [
  { id: 'sci-1', question: 'What is the chemical symbol for water?', options: ['H2O', 'CO2', 'O2', 'NaCl'], correctAnswer: 0 },
  { id: 'sci-2', question: 'Which gas do plants absorb from the atmosphere?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'], correctAnswer: 2 },
  { id: 'sci-3', question: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Platinum'], correctAnswer: 2 },
  { id: 'sci-4', question: 'Which planet is closest to the Sun?', options: ['Venus', 'Earth', 'Mars', 'Mercury'], correctAnswer: 3 },
  { id: 'sci-5', question: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi Apparatus'], correctAnswer: 1 },
  { id: 'sci-6', question: 'What is the boiling point of water at sea level?', options: ['90°C', '100°C', '110°C', '120°C'], correctAnswer: 1 },
  { id: 'sci-7', question: 'Which vitamin is produced when the human body is exposed to sunlight?', options: ['Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D'], correctAnswer: 3 },
  { id: 'sci-8', question: 'What is the main gas found in the air we breathe?', options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Argon'], correctAnswer: 1 },
  { id: 'sci-9', question: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], correctAnswer: 1 },
  { id: 'sci-10', question: 'What is the center of an atom called?', options: ['Proton', 'Electron', 'Neutron', 'Nucleus'], correctAnswer: 3 },
  { id: 'sci-11', question: 'Which organ in the human body pumps blood?', options: ['Lungs', 'Brain', 'Heart', 'Liver'], correctAnswer: 2 },
  { id: 'sci-12', question: 'What is the speed of light?', options: ['300,000 km/s', '150,000 km/s', '450,000 km/s', '600,000 km/s'], correctAnswer: 0 },
  { id: 'sci-13', question: 'Which element has the atomic number 1?', options: ['Helium', 'Oxygen', 'Hydrogen', 'Carbon'], correctAnswer: 2 },
  { id: 'sci-14', question: 'What is the largest organ in the human body?', options: ['Heart', 'Liver', 'Skin', 'Lungs'], correctAnswer: 2 },
  { id: 'sci-15', question: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correctAnswer: 1 },
  { id: 'sci-16', question: 'What is the chemical symbol for Gold?', options: ['Ag', 'Au', 'Fe', 'Pb'], correctAnswer: 1 },
  { id: 'sci-17', question: 'Which gas is most abundant in the Earth\'s atmosphere?', options: ['Oxygen', 'Nitrogen', 'Argon', 'Carbon Dioxide'], correctAnswer: 1 },
  { id: 'sci-18', question: 'What is the study of plants called?', options: ['Zoology', 'Botany', 'Geology', 'Astronomy'], correctAnswer: 1 },
  { id: 'sci-19', question: 'How many bones are in the adult human body?', options: ['206', '208', '210', '212'], correctAnswer: 0 },
  { id: 'sci-20', question: 'What is the nearest star to Earth?', options: ['Sirius', 'Alpha Centauri', 'Proxima Centauri', 'The Sun'], correctAnswer: 3 },
];
